name: dating
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_sign_in: ^5.1.0
  font_awesome_flutter: ^9.0.0
  connectivity: ^3.0.6

  country_code_picker: ^2.0.2
  pin_code_fields: ^7.3.0
  swipe_stack: ^1.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.17.0

  firebase_core: ^1.6.0

  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.3
  #geolocator: ^6.1.13
  #geolocator: ^7.6.2
  location: ^4.3.0
  #geocoder: ^0.2.1
  #image_picker: ^0.6.3+4 Old version doesn't work
  image_picker: ^0.8.4+2
  #image_cropper: ^1.2.1 Old doesn't woek
  image_cropper: ^1.4.1
  firebase_storage: ^10.0.3
  path_provider:
  #cached_network_image: ^2.0.0
  share: ^2.0.4
  firebase_messaging: ^10.0.7
  # flutter_webview_plugin: ^0.3.11
  in_app_purchase: ^1.0.8
  #rflutter_alert: ^2.0.4
  #agora_rtc_engine: 1.0.5
  permission_handler: ^8.1.6
  # flutter_ringtone_player: ^2.0.0
  shimmer: ^2.0.0
  #apple_sign_in: ^0.1.0
  url_launcher: ^6.0.10
  flutter_mapbox_autocomplete: ^2.0.0
  #firebase_admob: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "asset/logo.png" 


flutter:
  uses-material-design: true

  assets:
   - asset/auth/
   - asset/



  fonts:
    - family: Nunito
      fonts:
        - asset: asset/Nunito-Bold.ttf